---
- name : Create Datacenter
  hosts: 192.168.17.20

  tasks:
  - name: Create Datacenter
    local_action:
      module: vmware_datacenter
      hostname: florian.paris.local
      username: root 
      password: 'Florian2015!'
      datacenter_name: 'vDc_Ansible'
      state: present
      validate_certs: no
#    delegate_to: localhost
#    register: vmfacts
