---
- name : Create Cluster
  hosts: localhost

  tasks:
  - name: Create Cluster
    local_action:
      module: vmware_cluster
      hostname: 192.168.17.20
      username: root
      password: 'Florian2015!'
      datacenter_name: 'Florian_ANSIBLE'
      cluster_name: C_Florian
      enable_ha: yes
      enable_drs: yes
      enable_vsan: no
      validate_certs: no
#    delegate_to: localhost
#    register: vmfacts
