---
- name: Create a VM from a template
  hosts: localhost

  vars_prompt:
    - name: "florian.paris"
      prompt: "florian.paris"
      private: no
      default: "florian.paris"
    - name: "root"
      prompt: "root"
      private: no
      default: "Florian2015!"
    - name: "vcenter_pass"
      prompt: "Florian2015!"
      private: yes

  vars:
    datacenter: 'florian.paris'
    esxi_host: '192.168.17.10'
    notes: 'Created by Florian paris'
    vcenter_hostname: 192.168.17.20
    vcenter_user: root
    vcenter_pass: Florian2015!
    datastore: florian.paris
    network: VM Network
    memory: 20
    cpucount: 1
    osid: debin6_64Guest

  tasks:
  - name: Create a VM from template
    vmware_guest:
      hostname: 192.168.17.10
      username: root
      password: 'Espoir15'
      validate_certs: no
#      folder: /esxi3_local1/vm1/
      name: florian.parisVM
      state: present
      template: vm1
      disk:
      - size_gb: 1
        type: thin
        datastore: florian.paris
      hardware:
        memory_mb: 200
        num_cpus: 1
        scsi: paravirtual
#      networks:
#      - name: 'VM Network'
#        mac: aa:bb:dd:aa:00:14
      wait_for_ip_address: yes
#    delegate_to: localhost
    register: deploy
