---
- name : Create Datacenter
  hosts: localhost

  tasks:
  - name: Create Datacenter
    local_action:
      module: vmware_datacenter
      hostname: 192.168.17.20
      username: root 
      password: 'Florian2015!'
      datacenter_name: 'Florian_ANSIBLE'
      state: present
      validate_certs: no
#    delegate_to: localhost
#    register: vmfacts
