---
- name: Create a VM from a template
  hosts: localhost

  vars_prompt:
    - name: "vcenter_hostname"
      prompt: "Enter vcenter hostname"
      private: no
      default: "vc65.labvmware.local"
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
      default: "administrator@vsphere.local"
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
      private: yes

  vars:
    datacenter: 'florian.paris'
    esxi_host: '192.168.17.10'
    notes: 'Created by Florian PARIS'
    vcenter_hostname: 192.168.17.20
    vcenter_user: root
    vcenter_pass: Florian2015!
    datastore: vsanDatastore
    network: VM Network
    memory: 10
    cpucount: 1
    osid: debin6_64Guest

  tasks:
  - name: Create a VM Florian PARIS
    vmware_guest:
      hostname: florian.parisVM
      username: root
      password: 'Florian2015!'
      validate_certs: no
#      folder: /esxi3_local1/vm1/
      name: florian.parisVM
      state: present
      template: vm1
      disk:
      - size_gb: 1
        type: thin
        datastore: esxi3_local1
      hardware:
        memory_mb: 100
        num_cpus: 1
        scsi: paravirtual
#      networks:
#      - name: 'VM Network'
#        mac: aa:bb:dd:aa:00:14
      wait_for_ip_address: yes
#    delegate_to: localhost
    register: deploy
