---
- name: Create a VM from a template
  hosts: localhost
  
  tasks :
  ## Create VM
  - vsphere_guest:
     vcenter_hostname: 192.168.17.20
     username: "{{ root }}"
     password: "{{ Florian2015! }}"
     guest:  
     state: powered_off
     vm_disk:
       disk1:
         size_gb: 2
         type: thin
         datastore: datastore1
     vm_hardware:
       memory_mb: 204
       num_cpus: 1
       scsi: paravirtual
       osid: rhel6_64Guest     
     esxi:
      datacenter: 192.168.17.10
      hostname: 192.168.17.10 
