---
- name : Gather all registered virtual machines
  hosts: localhost

  vars_prompt:
    - name: "Florian2015!"
      prompt: "192.168.17.20"
      private: no

  tasks:
  - name: Gather all registered virtual machines
    vmware_vm_facts:
      hostname: 192.168.17.20
      username: root
      password: '{{ Florian2015! }}'
      validate_certs: no
    delegate_to: localhost
    register: vmfacts
